### PR TITLE
Run cleanup in a background goroutine without retry [K8SSAND-940]

### LINKED ISSUE #186: K8SSAND-940 ⁃ #186 - Scaling can trigger endless cleanup loop
**What happened?**

After a scaling operation cluster went into a bad state of an endless loop of triggering cleanups, cleanup is triggered but is reported back as failed in EP, due to this error the API call `DatacenterScalingUp` state is not reset causing another multiple round of cleanups. 

```
{"level":"error","ts":1632913707.7406483,"logger":"reconciliation_handler","msg":"unable to perform request to Node Management Endpoint","requestNamespace":"prod","requestName":"xxxx-dc1","loopID":"64424726-be90-45af-98a8-2b018e71de1b","namespace":"prod","datacenterName":"xxxxx-dc1","clusterName":"xxxx-dse","error":"Post \"http://x.x.x.x:8080/api/v0/ops/keyspace/cleanup\": context deadline exceeded","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/datastax/cass-operator/operator/pkg/httphelper.callNodeMgmtEndpoint\n\t/cass-operator/operator/pkg/httphelper/client.go:349\ngithub.com/datastax/cass-operator/operator/pkg/httphelper.(*NodeMgmtClient).CallKeyspaceCleanupEndpoint\n\t/cass-operator/operator/pkg/httphelper/client.go:237\ngithub.com/datastax/cass-operator/operator/pkg/reconciliation.(*ReconciliationContext).cleanupAfterScaling\n\t/cass-operator/operator/pkg/reconciliation/reconcile_racks.go:2090\ngithub.com/datastax/cass-operator/operator/pkg/reconciliation.(*ReconciliationContext).CheckClearActionConditions\n\t/cass-operator/operator/pkg/reconciliation/reconcile_racks.go:2135\ngithub.com/datastax/cass-operator/operator/pkg/reconciliation.(*ReconciliationContext).ReconcileAllRacks\n\t/cass-operator/operator/pkg/reconciliation/reconcile_racks.go:2353\ngithub.com/datastax/cass-operator/operator/pkg/reconciliation.(*ReconciliationContext).calculateReconciliationActions\n\t/cass-operator/operator/pkg/reconciliation/handler.go:166\ngithub.com/datastax/cass-operator/operator/pkg/reconciliation.(*ReconcileCassandraDatacenter).Reconcile\n\t/cass-operator/operator/pkg/reconciliation/handler.go:269\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:88"}
```

**Did you expect to see something different?**

There should be a way to stop cleanups. It is understood that somehow the cleanup is wrongly reported as failing. However, there needs to be a way to get out of that loop.

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Cass Operator version:

    `Insert image tag or Git SHA here`
    
    * Kubernetes version information:    `kubectl version`
    * Kubernetes cluster kind:```insert how you created your cluster: kops, bootkube, etc.

```

* Manifests:

```

insert manifests relevant to the issue

```

* Cass Operator Logs:

```

insert Cass Operator logs relevant to the issue here
```

**Anything else we need to know?**:



┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-940) by [Unito](https://www.unito.io)
┆Reviewer: John Sanda
┆fixVersions: cass-operator-1.9.0
┆friendlyId: K8SSAND-940
┆priority: Medium

### PR DESCRIPTION
**Pull request by burmanm**
**What this PR does**:
Runs the cleanup process after ScalingUp in a goroutine. This executes and logs errors, but does not retry the cleanup process if it fails. The timeout is set to infinite.

Note, this means the ScalingUp process is marked as finished before the cleanup has completed.

**Which issue(s) this PR fixes**:
Fixes #186

**Checklist**
- [ ] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CHANGELOG.md updated (not required for documentation PRs)
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by burmanm** [comment]
Actually.. don't merge or review. From what I can see in Cassandra 4.0 source code, we can do this better..

**Comment by burmanm** [comment]
@jsanda This hopefully now solves the cleanup issue in a sane way.. ready for review.

File: pkg/reconciliation/reconcile_racks.go [hunk 1]
```diff
@@ -2093,12 +2094,146 @@ func (rc *ReconciliationContext) CheckConditionInitializedAndReady() result.Reco
 	return result.Continue()
 }
 
-func cleanupAfterScaling(nodeClient *httphelper.NodeMgmtClient, logger logr.Logger, pods []*corev1.Pod) {
-	for _, pod := range pods {
-		if err := nodeClient.CallKeyspaceCleanupEndpoint(pod, -1, "", nil); err != nil {
-			logger.Error(err, "error cleaning up after scaling datacenter", "Pod", pod.GetName())
+const (
+	podJobIdAnnotation     = "cassandra.datastax.com/job-id"
```
Comment (jsanda) [inline pkg/reconciliation/reconcile_racks.go:2097]: How come annotations instead of labels? I ask because I could see where label selector queries might be useful at some point.

File: pkg/reconciliation/reconcile_racks.go [hunk 2]
```diff
@@ -2092,16 +2094,152 @@ func (rc *ReconciliationContext) CheckConditionInitializedAndReady() result.Reco
...
+			// Pod isn't running anything at the moment, this pod should run next
+			jobId, err := rc.NodeMgmtClient.CallKeyspaceCleanup(pod, -1, "", nil)
+			if err != nil {
+				// We can retry this later, it will only restart the cleanup but won't otherwise hurt
+				return result.Error(err)
+			}
+			pod.Annotations[podJobHandler] = jobHandlerMgmtApi
+			pod.Annotations[podJobIdAnnotation] = jobId
+
+			err = rc.Client.Update(context.Background(), pod)
```
Comment (jsanda) [inline pkg/reconciliation/reconcile_racks.go]: Would `Patch` be better here? I don't think we should care about conflicts here. If the update fails due to a conflict and we requeue, do we wind up calling `rc.NodeMgmtClient.CallKeyspaceCleanup` again? And shouldn't be using `context.Background()`.

This makes me wonder if we should be setting a status right before calling `CallKeyspaceCleanup` to indicate that we are about to start the operation. We would check for that status before making the call. If it is set, then we should check to see if the job is already in progress before calling `CallKeyspaceCleanup`.

File: pkg/reconciliation/reconcile_racks.go [hunk 3]
```diff
@@ -2092,16 +2094,152 @@ func (rc *ReconciliationContext) CheckConditionInitializedAndReady() result.Reco
...
+		} else {
+			jobId := strconv.Itoa(idx)
+
+			// This pod should run next, mark it
+			pod.Annotations[podJobHandler] = oplabels.ManagedByLabelValue
+			pod.Annotations[podJobIdAnnotation] = jobId
+
+			err = rc.Client.Update(context.Background(), pod)
+			if err != nil {
+				rc.ReqLogger.Error(err, "Pod", pod)
```
Comment (jsanda) [inline pkg/reconciliation/reconcile_racks.go]: Could we put a more descriptive message here indicating that we failed to add annotations?

File: pkg/reconciliation/reconcile_racks.go [hunk 4]
```diff
@@ -2092,16 +2094,152 @@ func (rc *ReconciliationContext) CheckConditionInitializedAndReady() result.Reco
...
+					// Pod is currently processing something, or has finished processing.. update the status
+					details, err := rc.NodeMgmtClient.JobDetails(pod, podJobId)
+					if err != nil {
+						rc.ReqLogger.Error(err, "Could not get JobDetails for pod", "Pod", pod)
+						return result.Error(err)
+					}
+
+					if details.Id == "" {
+						// This job was not found, pod most likely restarted. Let's retry..
+						delete(pod.Annotations, podJobIdAnnotation)
```
Comment (jsanda) [inline pkg/reconciliation/reconcile_racks.go:2148]: Would patch be better here? We don't need to worry about conflicts do we?

Shouldn't be using `context.Background()`.

File: pkg/reconciliation/reconcile_racks.go [hunk 5]
```diff
@@ -2092,16 +2094,152 @@ func (rc *ReconciliationContext) CheckConditionInitializedAndReady() result.Reco
...
+						err = rc.Client.Update(context.Background(), pod)
+						if err != nil {
+							return result.Error(err)
+						}
+						return result.RequeueSoon(2)
+					} else if details.Status == podJobError {
+						// Log the error, move on
+						rc.ReqLogger.Error(fmt.Errorf("cleanup failed: %s", details.Error), "Pod", pod)
+						pod.Annotations[podJobStatusAnnotation] = podJobError
+						err = rc.Client.Update(context.Background(), pod)
```
Comment (jsanda) [inline pkg/reconciliation/reconcile_racks.go]: Would patch be better here? We don't need to worry about conflicts do we?

File: pkg/reconciliation/reconcile_racks.go [hunk 6]
```diff
@@ -2092,16 +2094,152 @@ func (rc *ReconciliationContext) CheckConditionInitializedAndReady() result.Reco
...
+						if err != nil {
+							return result.Error(err)
+						}
+						continue
+					} else if details.Status == podJobCompleted {
+						// Pod has finished, remove the job_id and let us move to the next pod
+						pod.Annotations[podJobStatusAnnotation] = podJobCompleted
+						err = rc.Client.Update(context.Background(), pod)
```
Comment (jsanda) [inline pkg/reconciliation/reconcile_racks.go]: Would patch be better here? We don't need to worry about conflicts do we? 

Shouldn't be using `context.Background()`.

**Review by jsanda — COMMENTED** [review]
@burmanm I did an initial review of `cleanupAfterScaling()` with a focus on the code path for async cleanup. I'll follow with reviews of other parts later.

File: pkg/reconciliation/reconcile_racks.go [hunk 7]
```diff
@@ -2092,16 +2094,152 @@ func (rc *ReconciliationContext) CheckConditionInitializedAndReady() result.Reco
...
+				return result.Error(err)
+			}
+		} else {
+			jobId := strconv.Itoa(idx)
+
+			// This pod should run next, mark it
+			pod.Annotations[podJobHandler] = oplabels.ManagedByLabelValue
+			pod.Annotations[podJobIdAnnotation] = jobId
+
+			err = rc.Client.Update(context.Background(), pod)
```
Comment (jsanda) [inline pkg/reconciliation/reconcile_racks.go]: Would patch be better here? We don't need to worry about conflicts do we? 

Shouldn't be using `context.Background()`.

File: pkg/reconciliation/reconcile_racks.go [hunk 8]
```diff
@@ -2092,16 +2094,152 @@ func (rc *ReconciliationContext) CheckConditionInitializedAndReady() result.Reco
...
+			if err != nil {
+				// We can retry this later, it will only restart the cleanup but won't otherwise hurt
+				return result.Error(err)
+			}
+			pod.Annotations[podJobHandler] = jobHandlerMgmtApi
+			pod.Annotations[podJobIdAnnotation] = jobId
+
+			err = rc.Client.Update(context.Background(), pod)
+			if err != nil {
+				rc.ReqLogger.Error(err, "Pod", pod)
```
Comment (jsanda) [inline pkg/reconciliation/reconcile_racks.go]: Could we put a more descriptive message here indicating that we failed to add annotations?

File: pkg/reconciliation/reconcile_racks.go [hunk 9]
```diff
@@ -2092,16 +2094,152 @@ func (rc *ReconciliationContext) CheckConditionInitializedAndReady() result.Reco
...
+	podJobWaiting   = "WAITING"
+)
+
+var (
+	jobRunner chan int = make(chan int, 1)
+)
+
+func (rc *ReconciliationContext) cleanupAfterScaling() result.ReconcileResult {
+	// We sort to ensure we process the pods in the same order
+	sort.Slice(rc.dcPods, func(i, j int) bool {
```
Comment (jsanda) [inline pkg/reconciliation/reconcile_racks.go:2113]: If a pod is deleted and recreated then the order changes. It may not be a big deal but to keep things consistent and predictable, what do you think about sort first by rack and then by pod name? We wouldn't need to use the rack for just for sorting purposes, it helps ensure do one rack at a time.

File: pkg/reconciliation/reconcile_racks_test.go [hunk 10]
```diff
@@ -1474,3 +1475,219 @@ func Test_callPodEndpoint_RequestFail(t *testing.T) {
...
+	r := rc.cleanupAfterScaling()
+	if r != result.RequeueSoon(2) {
+		t.Fatalf("expected result of result.RequeueSoon(2) but got %s", r)
+	}
+
+	// Mock jobDetails to return success
+	mockJobDetailsResponse(mockHttpClient)
+
+	// Job should be done on the next pass
+	assert.Eventually(func() bool {
```
Comment (jsanda) [inline pkg/reconciliation/reconcile_racks_test.go:1509]: There is no need for `Eventually` here. I tested without multiple times and the test ran fine. I changed line 1519 to be `assert.Equal(r, result.Continue())`.

**Review by jsanda — COMMENTED** [review]
I just completed of `cleanupAfterScaling` with focus on the code path that doesn't support async cleanup through management-api. I also started looking at unit tests. More to come...

File: pkg/reconciliation/reconcile_racks.go (hunk 1 above)
Comment (burmanm) [reply pkg/reconciliation/reconcile_racks.go:2097]: Annotations seem to be intended place for this kind of data based on the Kubernetes docs. Why would you need label selectors (although we can always change these later if such need arises - these are dynamic information in any case)

File: pkg/reconciliation/reconcile_racks.go (hunk 2 above)
Comment (burmanm) [reply pkg/reconciliation/reconcile_racks.go]: We're checking the status before we start the job. The previous part:

``if podJobId, found := pod.Annotations[podJobIdAnnotation]; found {``

is ran before this, so if the podJobId is set, then we will not run this part of the code. We set the status here to indicate the jobId (so we can search for it), and we won't get that id before we actually send the request for a job.

If this Update fails and we come back to this part, then the new CallKeyspaceCleanup shouldn't really matter.

File: pkg/reconciliation/reconcile_racks.go (hunk 1 above)
Comment (jsanda) [reply pkg/reconciliation/reconcile_racks.go:2097]: I was thinking labels for a couple reasons. First, the job-id and the job-status identify state about the pod that clients may want to query. I could use a label selector query to track the overall progress of the operation. Secondly, and more importantly, I wonder if labels would be more consistent with what is done elsewhere in cass-operator, namely with the `cassandra.datastax.com/node-state` label.

File: pkg/reconciliation/reconcile_racks_test.go (hunk 10 above)
Comment (jsanda) [reply pkg/reconciliation/reconcile_racks_test.go:1509]: I hadn't looked at the other tests when I added that comment. I went over the other tests and `Eventually` is needed for them. Even if it isn't needed here, it makes sense from a consistency standpoint.

File: pkg/reconciliation/reconcile_racks.go [hunk 11]
```diff
@@ -2092,16 +2094,152 @@ func (rc *ReconciliationContext) CheckConditionInitializedAndReady() result.Reco
...
+					}
+
+					if details.Id == "" {
+						// This job was not found, pod most likely restarted. Let's retry..
+						delete(pod.Annotations, podJobIdAnnotation)
+						err = rc.Client.Update(context.Background(), pod)
+						if err != nil {
+							return result.Error(err)
+						}
+						return result.RequeueSoon(2)
```
Comment (jsanda) [inline pkg/reconciliation/reconcile_racks.go]: Could we go retry the operation at this point without a requeue?

File: pkg/reconciliation/reconcile_racks.go (hunk 9 above)
Comment (burmanm) [reply pkg/reconciliation/reconcile_racks.go:2113]: Well, I added now an option that sorts by rack and by name. Would that work?

File: pkg/reconciliation/reconcile_racks.go (hunk 11 above)
Comment (burmanm) [reply pkg/reconciliation/reconcile_racks.go]: Could, but it made the code and logic look a lot less readable - and I don't think it's a very common issue to happen. Especially since if the pod restarted, it probably can't restart the job very soon in any case.

Comment (jsanda) [reply pkg/reconciliation/reconcile_racks.go]: I agree about it making the code less readable. I'm good here.

File: pkg/reconciliation/reconcile_racks.go [hunk 12]
```diff
@@ -2092,16 +2093,163 @@ func (rc *ReconciliationContext) CheckConditionInitializedAndReady() result.Reco
...
+						// Pod has finished, remove the job_id and let us move to the next pod
+						pod.Annotations[podJobStatusAnnotation] = podJobCompleted
+						err = rc.Client.Patch(rc.GetContext(), pod, podPatch)
+						if err != nil {
+							return result.Error(err)
+						}
+						continue
+					} else if details.Status == podJobWaiting {
+						// Job is still running or waiting
+						return result.RequeueSoon(1)
```
Comment (jsanda) [inline pkg/reconciliation/reconcile_racks.go]: As we know cleanup can take a considerable amount of time. Is there a reason to use such a short delay here?

File: pkg/reconciliation/reconcile_racks.go [hunk 13]
```diff
@@ -2092,16 +2093,163 @@ func (rc *ReconciliationContext) CheckConditionInitializedAndReady() result.Reco
...
+					}
+				} else {
+					// This pod has finished since it has a status
+					continue
+				}
+			} else {
+				if len(jobRunner) > 0 {
+					// Something is still holding the worker
+					return result.RequeueSoon(2)
```
Comment (jsanda) [inline pkg/reconciliation/reconcile_racks.go]: As we know cleanup can take a considerable amount of time. Is there a reason to use such a short delay here?

File: pkg/reconciliation/reconcile_racks.go [hunk 14]
```diff
@@ -2092,16 +2093,163 @@ func (rc *ReconciliationContext) CheckConditionInitializedAndReady() result.Reco
...
+
+				err = rc.Client.Patch(rc.GetContext(), pod, podPatch)
+				if err != nil {
+					rc.ReqLogger.Error(err, "Failed to update local job's status", "Pod", targetPod)
+				}
+			}(pod)
 		}
+
+		// We have a job going on, return back later to check the status
+		return result.RequeueSoon(2)
```
Comment (jsanda) [inline pkg/reconciliation/reconcile_racks.go]: Is there a reason to use such a short delay here?

File: pkg/reconciliation/reconcile_racks.go (hunk 12 above)
Comment (burmanm) [reply pkg/reconciliation/reconcile_racks.go]: I modified it to 10 seconds now. But I'd rather not increase more, since it slows down scale up process and blocks other changes, so we'd want it somewhat responsive despite some small additional load.

**Comment by jsanda** [comment]
@burmanm looks like unit tests need to be updated with the change to use Patch.

**Review by jsanda — APPROVED** [review]
