### PR TITLE
Verify the ReplaceNodes pod names

### LINKED ISSUE #315: K8SSAND-1423 ⁃ cass-operator becomes partially inoperable if replaceNodes has a wrong pod name
**What happened?**
cass-operator loses part of its functionality after the user mistakenly supplied a wrong pod name under the `spec.replaceNodes` field. For example, the operator will fail to decommission nodes nor do a rolling restart. This is because in the reconciliation loop, the operator re-queues the request if the `status.NodeReplacements` is nonempty before reconciling many other functionalities. Since the pod name under the `status.NodeReplacements` does not exist, the operator is never able to clear the `status.NodeReplacements`. This causes the operator becomes partially nonfunctional.

**Did you expect to see something different?**
The operator should be robust and still able to reconcile other functionalities even when the user submitted a wrong pod name for `spec.replaceNodes`. Or the operator should do a sanity check on `spec.replaceNodes` to prevent from getting stuck.

**How to reproduce it (as minimally and precisely as possible)**:

1. Deploy the cass-operator
1. Deploy the CassandraDatacenter using this yaml, `kubectl apply -f sample.yaml`:

```yaml
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: cassandra-datacenter
spec:
  clusterName: cluster1
  serverType: cassandra
  serverVersion: 3.11.7
  size: 1
  storageConfig:
    cassandraDataVolumeClaimSpec:
      accessModes:


* ReadWriteOnce
resources:
requests:
storage: 3Gi
storageClassName: server-storage
```

1. Provide an invalid pod name for `spec.replaceNodes`, `kubectl apply -f sample.yaml`

```yaml
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
name: cassandra-datacenter
spec:
clusterName: cluster1
serverType: cassandra
serverVersion: 3.11.7
size: 1
storageConfig:
cassandraDataVolumeClaimSpec:
accessModes:
* ReadWriteOnce
resources:
requests:
storage: 3Gi
storageClassName: server-storage
replaceNodes:
* rtiisajufx
```

1. Try request rolling restart, `kubectl apply -f sample.yaml`:

```yaml
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
name: cassandra-datacenter
spec:
clusterName: cluster1
serverType: cassandra
serverVersion: 3.11.7
size: 1
storageConfig:
cassandraDataVolumeClaimSpec:
accessModes:
* ReadWriteOnce
resources:
requests:
storage: 3Gi
storageClassName: server-storage
replaceNodes:
* rtiisajufx
rollingRestartRequested: true
```

1. Observe that the cluster does not restart

**Environment**

* Cass Operator version:

`docker.io/k8ssandra/cass-operator:v1.9.0`
    
    

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

kind

* Manifests:

```
See above yaml manifests in the reproduce steps
```

**Anything else we need to know?**:
The bug is caused because the operator keeps re-queueing the request while the `status.NodeReplacements` cannot get cleared due to wrong pod name. We suggest to sanitize the `spec.replaceNodes` field to make the operator robust.

┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-1423) by [Unito](https://www.unito.io)
┆affectedVersions: cass-operator-1.9.0
┆friendlyId: K8SSAND-1423
┆priority: Medium

### PR DESCRIPTION
**Pull request by burmanm**
**What this PR does**:
Whenever user sets pod names to the Spec.ReplaceNodes, instead of blindly trusting the input, verify that the pod actually exists in our managed dc before moving it to the NodeReplacements.

**Which issue(s) this PR fixes**:
Fixes #315

**Checklist**
- [ ] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CHANGELOG.md updated (not required for documentation PRs)
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: pkg/reconciliation/reconcile_racks.go [hunk 1]
```diff
@@ -1070,19 +1070,29 @@ func (rc *ReconciliationContext) startReplacePodsIfReplacePodsSpecified() error
...
+					break
+				}
+			}
+			rc.ReqLogger.Error(fmt.Errorf("invalid pod name in ReplaceNodes"), "Rejected ReplaceNode entry, pod does not exist in the Datacenter", "PodName", podName)
+		}
 
-		_ = rc.setCondition(
-			api.NewDatacenterCondition(api.DatacenterReplacingNodes, corev1.ConditionTrue))
+		if len(dc.Status.NodeReplacements) > 0 {
+			podNamesString := strings.Join(dc.Spec.ReplaceNodes, ", ")
```
Comment (adutra) [inline pkg/reconciliation/reconcile_racks.go]:
```suggestion
			podNamesString := strings.Join(dc.Status.NodeReplacements, ", ")
```

File: pkg/reconciliation/reconcile_racks_test.go [hunk 2]
```diff
@@ -1549,3 +1549,55 @@ func TestStripPassword(t *testing.T) {
...
+	assert.NoError(err)
+	assert.Equal(0, len(rc.Datacenter.Status.NodeReplacements))
+
+	rc.Datacenter.Spec.ReplaceNodes = []string{""}
+	err = rc.startReplacePodsIfReplacePodsSpecified()
+	assert.NoError(err)
+	assert.Equal(0, len(rc.Datacenter.Status.NodeReplacements))
+	assert.Equal(0, len(rc.Datacenter.Spec.ReplaceNodes))
+
+	rc.Datacenter.Spec.ReplaceNodes = []string{"dc1-default-sts-3"} // Does not exists
```
Comment (adutra) [inline pkg/reconciliation/reconcile_racks_test.go]:
```suggestion
	rc.Datacenter.Spec.ReplaceNodes = []string{"dc1-default-sts-3"} // Does not exist
```

**Review by adutra — APPROVED** [review]

File: pkg/reconciliation/reconcile_racks.go (hunk 1 above)
Comment (burmanm) [reply pkg/reconciliation/reconcile_racks.go]: Actually this was intended to log only the new additions in the Spec. However, both lines actually create incorrect log line (Status can show some old node also that hasn't finished yet, while Spec would show the one that we just rejected..)
