### PR TITLE
Set the ServiceName for new StatefulSets

### LINKED ISSUE #304: K8SSAND-1349 ⁃ Hostname lookups on Cassandra pods fail
**What happened?**
I created a CassandraDatacenter with cluster name of test and no racks and 3 C* nodes. This results in the following pods:

* test-dc1-default-sts-0
* test-dc1-default-sts-1
* test-dc1-default-sts-2

As per the Kubernetes [docs](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-network-id) there should be a DNS record for each pod such that the following should be resolvable (assuming the CassandraDatacenter is created in cass-operator namespace),

`test-dc1-default-sts-0.test-dc1-all-pods-service.cass-operator.svc.cluster.local`

Note that `test-dc1-all-pods-service` is the name of the headless service with which cass-operator configures the StatefulSet. Specifically, cass-operator sets the `StatefulSet.Spec.ServiceName` field to the name of the all-pods service.

The DNS lookup fails because the `StatefulSet.Spec.ServiceName` is set to the empty string.

**Did you expect to see something different?**
The `StatefulSet.Spec.ServiceName` property should be set to the all-pods service name then hostname lookups will work.

**How to reproduce it (as minimally and precisely as possible)**:
Create a CassandraDatacenter, e.g., 

```yaml
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
spec:
  clusterName: test
  config:
    jvm-server-options:
      initial_heap_size: 512M
      max_heap_size: 512M
  serverType: cassandra
  serverVersion: 4.0.3
  size: 1
  storageConfig:
    cassandraDataVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: standard
```

Wait for the operator to create the StatefulSet and then see that the `ServiceName` property is not set.

**Environment**

* Cass Operator version:

```
I believe this affects versions 1.7.1 to 1.10.1
```

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1349) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1349
┆priority: Medium

### PR DESCRIPTION
**Pull request by jsanda**
**What this PR does**:

**Which issue(s) this PR fixes**:
Fixes #304

**Checklist**
- [x] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CHANGELOG.md updated (not required for documentation PRs)
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: pkg/reconciliation/construct_statefulset.go [hunk 1]
```diff
@@ -179,7 +179,7 @@ func newStatefulSetForCassandraDatacenter(
 	}
 	result.Annotations = map[string]string{}
 
-	if sts != nil && sts.Spec.ServiceName != result.Spec.ServiceName {
+	if sts != nil && sts.Spec.ServiceName != "" && sts.Spec.ServiceName != result.Spec.ServiceName {
```
Comment (burmanm) [inline pkg/reconciliation/construct_statefulset.go:182]: This would indicate that the dc.GetAllPodsServiceName() is returning empty string (set in the line 174)

Comment (burmanm) [reply pkg/reconciliation/construct_statefulset.go:182]: Wonder what would've created the empty sts originally

File: CHANGELOG.md [hunk 2]
```diff
@@ -30,6 +30,7 @@ Changelog for Cass Operator, new PRs should update the `main / unreleased` secti
 * [BUGFIX] [#272](https://github.com/k8ssandra/cass-operator/issues/272) Strip password (if it has one) from CreateRole
 * [BUGFIX] [#254](https://github.com/k8ssandra/cass-operator/pull/254) Safely set annotation on datacenter in config secret
 * [BUGFIX] [#261](https://github.com/k8ssandra/cass-operator/issues/261) State of decommission can't be detected correctly if the RPC address is removed from endpoint state during decommission, but before it's finalized.
+* [BUGFIX] [#304](https://github.com/k8ssandra/cass-operator/issues/304) Hostname lookups on Cassandra pods fail
```
Comment (burmanm) [inline CHANGELOG.md]: This is in wrong place, it should be placed under ## unreleased

File: pkg/reconciliation/construct_statefulset.go (hunk 1 above)
Comment (jsanda) [reply pkg/reconciliation/construct_statefulset.go:182]: Turns out we always start with an empty sts initially. Due to this bug for new CassandraDatacenters the `ServiceName` will always be empty string.

`dc.GetAllPodsServiceName()` does not return empty string.

**Review by burmanm — APPROVED** [review]
