### PR TITLE
Consolidate some probe code

### LINKED ISSUE #377: Probe wget calls are missing a timeout
**What happened?**
When management-api is configured to use mutual TLS authentication, we are unable to use Kubernetes' httpGet for liveness and readiness probes, since Kubernetes does not allow us to use mutual auth TLS. Thus, in this case we replace the calls by executing wget on the pod that then has access to both of these certificates (since they're mounted to the pods).

If the calls never reach the target for some reason, this wget call was never exiting itself. This caused multiple wget processes to live in the pod, as they would live longer than the interval for those calls.

**Did you expect to see something different?**
Each wget call should have a timeout that's shorter than (or equal to) the probing interval.

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Cass Operator version:

    `Insert image tag or Git SHA here`
    
    * Kubernetes version information:

    `kubectl version`
    * Kubernetes cluster kind:

```
insert how you created your cluster: kops, bootkube, etc.
```

* Manifests:

```
insert manifests relevant to the issue
```

* Cass Operator Logs:

```
insert Cass Operator logs relevant to the issue here
```

**Anything else we need to know?**:

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1667) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1667
┆priority: Medium

### PR DESCRIPTION
**Pull request by burmanm**
**What this PR does**:
Adds back the terminate test for drain test and consolidates from probe and presto hook URL paths.

**Which issue(s) this PR fixes**:
Fixes #377

**Checklist**
- [ ] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CHANGELOG.md updated (not required for documentation PRs)
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -214,7 +214,7 @@ endif
 
 .PHONY: cert-manager
 cert-manager: ## Install cert-manager to the cluster
-	kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.8.0/cert-manager.yaml
+	kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.8.2/cert-manager.yaml
```
Comment (jsanda) [inline Makefile:217]: It would be good to keep common deps in sync between cass-operator and k8ssandra-operator. Can you upgrade cert-manager in k8ssandra-operator as well?

File: pkg/httphelper/security.go [hunk 2]
```diff
@@ -171,7 +170,8 @@ func (provider *InsecureManagementApiSecurityProvider) BuildMgmtApiWgetAction(en
 			"wget",
 			"--output-document", "/dev/null",
 			"--no-check-certificate",
-			fmt.Sprintf("http://%s", endpoint),
+			"--timeout 20",
```
Comment (jsanda) [inline pkg/httphelper/security.go]: Should the timeout be configurable?

File: pkg/httphelper/security.go [hunk 3]
```diff
@@ -185,7 +185,8 @@ func (provider *ManualManagementApiSecurityProvider) BuildMgmtApiWgetAction(endp
 			"--certificate", tlsCrt,
 			"--private-key", tlsKey,
 			"--ca-certificate", caCertPath,
-			fmt.Sprintf("https://%s", endpoint),
+			"--timeout 20",
```
Comment (jsanda) [inline pkg/httphelper/security.go]: Should the timeout be configurable?

File: pkg/httphelper/security.go [hunk 4]
```diff
@@ -196,8 +197,9 @@ func (provider *InsecureManagementApiSecurityProvider) BuildMgmtApiWgetPostActio
 			"wget",
 			"--output-document", "/dev/null",
 			"--no-check-certificate",
+			"--timeout 20",
```
Comment (jsanda) [inline pkg/httphelper/security.go]: Should the timeout be configurable?

File: pkg/httphelper/security.go [hunk 5]
```diff
@@ -211,8 +213,9 @@ func (provider *ManualManagementApiSecurityProvider) BuildMgmtApiWgetPostAction(
 			"--certificate", tlsCrt,
 			"--private-key", tlsKey,
 			"--ca-certificate", caCertPath,
+			"--timeout 20",
```
Comment (jsanda) [inline pkg/httphelper/security.go]: Should the timeout be configurable?

**Comment by jsanda** [comment]
@burmanm  Can you also create an issue for this with some details on why the wget calls are made and why it's a good idea to add the timeouts?

File: pkg/httphelper/security.go (hunk 3 above)
Comment (burmanm) [reply pkg/httphelper/security.go]: Not really, we don't allow configuring other mgmt-api timeouts in the code either.

Comment (jsanda) [reply pkg/httphelper/security.go]: A hard coded value seems less than ideal. If someone, even for dev/testings needs to adjust it is going require building a new image. What about making it configurable through the operator config map?

Comment (burmanm) [reply pkg/httphelper/security.go]: That would make it inconsistent with the httpGet calls we have as well as all the client.go (management-api communications), they're not configurable either.

We can make a ticket to configure all those, but that will require quite a lot of work and break APIs for all users of management-api client.

Comment (burmanm) [reply pkg/httphelper/security.go]: I added a commit that allows it. It will break backwards compatibility, so I wouldn't backport it.

Comment (jsanda) [reply pkg/httphelper/security.go]: Before you pushed the commit I was about reply saying I am ok punting if you think it is unnecessary :)

**Comment by jsanda** [comment]
Changes look good other than the failing tests.
