### PR TITLE
Recreate StatefulSet if required for updates to StS

### LINKED ISSUE #304: K8SSAND-1349 ⁃ Hostname lookups on Cassandra pods fail
**What happened?**
I created a CassandraDatacenter with cluster name of test and no racks and 3 C* nodes. This results in the following pods:

* test-dc1-default-sts-0
* test-dc1-default-sts-1
* test-dc1-default-sts-2

As per the Kubernetes [docs](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-network-id) there should be a DNS record for each pod such that the following should be resolvable (assuming the CassandraDatacenter is created in cass-operator namespace),

`test-dc1-default-sts-0.test-dc1-all-pods-service.cass-operator.svc.cluster.local`

Note that `test-dc1-all-pods-service` is the name of the headless service with which cass-operator configures the StatefulSet. Specifically, cass-operator sets the `StatefulSet.Spec.ServiceName` field to the name of the all-pods service.

The DNS lookup fails because the `StatefulSet.Spec.ServiceName` is set to the empty string.

**Did you expect to see something different?**
The `StatefulSet.Spec.ServiceName` property should be set to the all-pods service name then hostname lookups will work.

**How to reproduce it (as minimally and precisely as possible)**:
Create a CassandraDatacenter, e.g., 

```yaml
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
spec:
  clusterName: test
  config:
    jvm-server-options:
      initial_heap_size: 512M
      max_heap_size: 512M
  serverType: cassandra
  serverVersion: 4.0.3
  size: 1
  storageConfig:
    cassandraDataVolumeClaimSpec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: standard
```

Wait for the operator to create the StatefulSet and then see that the `ServiceName` property is not set.

**Environment**

* Cass Operator version:

```
I believe this affects versions 1.7.1 to 1.10.1
```

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1349) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1349
┆priority: Medium

### LINKED ISSUE #311: K8SSAND-1410 ⁃ ScalingUp Status is not always removed
**What happened?**
While running scale_up integration test, I've noticed that the second / third cleanup task is not always created as it seems the DatacenterController thinks there's still an active one (and as such, no new one is required). There are few indicators why this could be happening:

```
1.6488026926732535e+09	ERROR	controller.cassandratask	Reconciler error	{"reconciler group": "control.k8ssandra.io", "reconciler kind": "CassandraTask", "name": "cleanup-1648802692", "namespace": "test-scale-up", "error": "Operation cannot be fulfilled on cassandratasks.control.k8ssandra.io \"cleanup-1648802692\": the object has been modified; please apply your changes to the latest version and try again"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266
```

That task did complete (the controller was able to handle it), but it indicates we have some concurrent update / missing refresh. The next one completed without issues, but on this run, the third one was never created - but there's no logging to indicate why this might have happened.

Sadly, we don't have CassandraDatacenter status logged in the test framework, so tracking why that might have happened is difficult. Tracking this in #312 

From further debugging, it seems to be that CassandraDatacenter stays in "ScalingUp" and updating and that's why CassandraTask is never created:

```yaml
  - lastTransitionTime: "2022-04-01T09:59:05Z"
    message: ""
    reason: ""
    status: "True"
    type: ScalingUp
  - lastTransitionTime: "2022-04-01T10:01:58Z"
    message: ""
    reason: ""
    status: "True"
    type: Updating
```

Yet there's no action going on in the cass-operator, since:

```
1.6488073383268092e+09  INFO    controllers.CassandraDatacenter.cassandradatacenter_controller.controller.cassandradatacenter-controller        All StatefulSets should now be reconciled.{"reconciler group": "cassandra.datastax.com", "reconciler kind": "CassandraDatacenter", "name": "dc2", "namespace": "test-scale-up", "namespace": "test-scale-up", "datacenterName": "dc2", "clusterName": "cluster2"}
```

**Did you expect to see something different?**

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Cass Operator version:

    `Insert image tag or Git SHA here`
    
    * Kubernetes version information:    `kubectl version`
    * Kubernetes cluster kind:```
insert how you created your cluster: kops, bootkube, etc.
```

* Manifests:

```
insert manifests relevant to the issue
```

* Cass Operator Logs:

```
insert Cass Operator logs relevant to the issue here
```

**Anything else we need to know?**:



┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1410) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1410
┆priority: Medium

### LINKED ISSUE #312: K8SSAND-1409 ⁃ Test dump does not output all objects
**What is missing?**
After running the test, the build directory has information such as operator logs, pod logs and some objects. However, we miss all our CRD statuses and that makes it difficult to track last status of an object, or which objects were actually created and how they looked.

**Why do we need it?**
To improve debug of test runs.

**Environment**

* Cass Operator version:

    `Insert image tag or Git SHA here`
    
    **Anything else we need to know?**:

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1409) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1409
┆priority: Medium

### PR DESCRIPTION
**Pull request by burmanm**
**What this PR does**:

**Which issue(s) this PR fixes**:
Fixes #312
Fixes #311 
Fixes #304 

**Checklist**
- [ ] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CHANGELOG.md updated (not required for documentation PRs)
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: pkg/reconciliation/reconcile_racks.go [hunk 1]
```diff
@@ -408,6 +409,37 @@ func (rc *ReconciliationContext) CheckRackForceUpgrade() result.ReconcileResult
 	return result.Done()
 }
 
+func (rc *ReconciliationContext) deleteStatefulSet(statefulSet *appsv1.StatefulSet) error {
+	// Remove reference to the StatefulSet from pods
```
Comment (jsanda) [inline pkg/reconciliation/reconcile_racks.go]: Can you remove this comment block?

File: pkg/reconciliation/reconcile_racks.go [hunk 2]
```diff
@@ -2222,7 +2254,7 @@ func (rc *ReconciliationContext) CheckClearActionConditions() result.ReconcileRe
 	// Explicitly handle scaling up here because we want to run a cleanup afterwards
 	if dc.GetConditionStatus(api.DatacenterScalingUp) == corev1.ConditionTrue {
 		// Call the first node with cleanup, wait until it has finished and then move on to the next pod..
-		if res := rc.cleanupAfterScaling(); !res.Completed() {
+		if res := rc.cleanupAfterScaling(); res.Completed() {
```
Comment (jsanda) [inline pkg/reconciliation/reconcile_racks.go:2238]: Can you explain this? I don't follow. I read this as, if the cleanup task is done then return and do not flip the status on the ScalingUp condition.

File: pkg/reconciliation/reconcile_racks.go [hunk 3]
```diff
@@ -275,11 +271,14 @@ func (rc *ReconciliationContext) CheckRackPodTemplate() result.ReconcileResult {
...
 			err = rc.Client.Update(rc.Ctx, statefulSet)
 			if err != nil {
-				logger.Error(
-					err,
-					"Unable to perform update on statefulset for config",
-					"statefulSet", statefulSet)
-				return result.Error(err)
+				if errors.IsInvalid(err) {
+					if err = rc.deleteStatefulSet(statefulSet); err != nil {
+						// logger.Error(err, "Failed to delete the StatefulSet", "Invalid", errors.IsInvalid(err), "Forbidden", errors.IsForbidden(err))
```
Comment (jsanda) [inline pkg/reconciliation/reconcile_racks.go]: Can you remove this commented out line?

File: pkg/reconciliation/reconcile_racks.go (hunk 2 above)
Comment (burmanm) [reply pkg/reconciliation/reconcile_racks.go:2238]: No, that's what I thought it would do also when I wrote it originally. That's not what Completed() in result is however. Completed() in this case means the processing should not continue. ``res.Completed()`` is true when a) Error happens or b) Requeue is requested. If the cleanup is done, the cleanupAfterScaling returns ``result.Continue()`` which actually has ``res.Completed()`` returning false.

Comment (jsanda) [reply pkg/reconciliation/reconcile_racks.go:2238]: Thanks for the explanation 👍

File: tests/util/kubectl/kubectl.go [hunk 4]
```diff
@@ -351,6 +351,43 @@ func DumpLogs(path string, namespace string) KCmd {
 	return KCmd{Command: "cluster-info", Args: args, Flags: flags}
 }
 
+// DumpClusterInfo Executes `kubectl cluster-info dump -o yaml` on each cluster. The output
+// is stored under <project-root>/build/test.
+func DumpClusterInfo(path string, namespace string) error {
```
Comment (jsanda) [inline tests/util/kubectl/kubectl.go:356]: It would be nice to put the output under a test-specific subdirectory. I realize though that it would require passing the test name through several functions in the ginkgo package. If there is a desire to do that it could be done in a later PR.

File: CHANGELOG.md [hunk 5]
```diff
@@ -13,9 +13,12 @@ Changelog for Cass Operator, new PRs should update the `main / unreleased` secti
 
 * [CHANGE] [#183](https://github.com/k8ssandra/cass-operator/issues/183) Move from PodDisruptionBudget v1beta1 to v1 (min. Kubernetes version 1.21)
 * [CHANGE] [#264](https://github.com/k8ssandra/cass-operator/issues/264) Generate PodTemplateSpec in CassandraDatacenter with metadata
-* [ENHANCEMENT] []() Update to Go 1.17 with updates to dependencies: Kube 1.23.4 and controller-runtime 0.11.1 
+* [FEATURE] [#309](https://github.com/k8ssandra/cass-operator/pull/309) If StatefulSets are modified in a way that they can't be updated directly, recreate them with new specs
```
Comment (jsanda) [inline CHANGELOG.md:16]: Do you really consider this a feature? :)

File: tests/util/kubectl/kubectl.go (hunk 4 above)
Comment (burmanm) [reply tests/util/kubectl/kubectl.go:356]: It is done already (the path is test specific with date and test name)

File: CHANGELOG.md (hunk 5 above)
Comment (burmanm) [reply CHANGELOG.md:16]: Yes. It's not available in Kubernetes ;)

Comment (jsanda) [reply CHANGELOG.md:16]: Curious, outside of the bug fix what is the use case here that would be considered a feature?

**Review by jsanda — APPROVED** [review]
I created a CassandraDatacenter using 1.10.1. Then I updated to the latest in your branch and verified that the `ServiceName` property of the StatefulSet was updated as expected.

File: CHANGELOG.md (hunk 5 above)
Comment (burmanm) [reply CHANGELOG.md:16]: We've modified the StatefulSet before, but previously it has been protected by not making the changes if it was something else previously. I'd say this is the intended behavior of StatefulSets as of now. Recreating it is more a workaround for not being able to modify it and as such I don't think it's a bugfix.
