### PR TITLE
EndpointState has incorrect json key (fixes #298)

### LINKED ISSUE #298: K8SSAND-1327 ⁃ `EndpointState` has incorrect json key
**What happened?**
`EndpointState` has incorrect json key in struct (https://github.com/k8ssandra/cass-operator/blob/77eecf9ecbe40832fa6310eacb8781d49bdb1d22/pkg/httphelper/client.go#L64). Expected that `GetRpcAddress()` would resolve to a valid IP address for a node, but was returning "". Should default to `NATIVE_TRANSPORT_ADDRESS` when no rpc address is returned for an endpoint, but the cass-management-api call actually returns `NATIVE_ADDRESS_AND_PORT`

**Did you expect to see something different?**
Expected the value from `NATIVE_ADDRESS_AND_PORT` to be returned in `GetRpcAddress` call, not an empty string

**How to reproduce it (as minimally and precisely as possible)**:
execute `curl http://localhost:8080/api/v0/metadata/endpoints` from a pod to see the json value returned and the presence of `NATIVE_ADDRESS_AND_PORT` instead of `NATIVE_TRANSPORT_ADDRESS`

Reproduce failed node replacement (how the issue was found):

1. Spin up a cassandra cluster that uses the following image `k8ssandra/cass-management-api:4.0.1-v0.1.30`
1. Manually execute the commands from the following `node_replace` test (https://github.com/k8ssandra/cass-operator/blob/master/tests/node_replace/node_replace_suite_test.go)
1. The API call to start the new node will have `replaceIP: ""` instead of the actual replace address

**Environment**
AWS

* Cass Operator version:

    `"docker.io/k8ssandra/cass-operator:v1.9.0"`
    
    * Kubernetes version information:    `Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:33:37Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"darwin/amd64"}Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.9-dd.1", GitCommit:"f71f8bd315fe5d6d7d44b619bd9364362fb8d9a8", GitTreeState:"clean", BuildDate:"2021-08-06T21:03:07Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}`
    * Kubernetes cluster kind:```
k8ssandra deployment 
```

* Manifests:

```
insert manifests relevant to the issue
```

* Cass Operator Logs:

```
controllers.CassandraDatacenter    calling Management API start node - POST /api/v0/lifecycle/start    {"cassandradatacenter": "cassandra-k8ssandra-seid/dc1", "requestNamespace": "cassandra-k8ssandra-seid", "requestName": "dc1", "loopID": "a15cf01d-43c1-4ae0-a41c-ab58ef7cb24c", "namespace": "cassandra-k8ssandra-seid", "datacenterName": "dc1", "clusterName": "k8ssandra-seid", "pod": "k8ssandra-seid-dc1-rack1-sts-0", "podIP": "xx.xx.xx.xx", "replaceIP": ""}
```

**Anything else we need to know?**:
Further discussion/debugging in discord channel



┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1327) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1327
┆priority: Medium

### PR DESCRIPTION
**Pull request by adutra**
**What this PR does**:

Fixes incorrect RPC address for Cassandra 4.0.

**Which issue(s) this PR fixes**:
Fixes #298

**Checklist**
- [x] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CHANGELOG.md updated (not required for documentation PRs)
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by burmanm** [comment]
This needs a test update, the node_replace test uses 3.11.10.

**Comment by burmanm** [comment]
I meant the e2e test. There's no verification that the feature actually works with 4.x, only that we fetch different JSON key.

File: tests/util/ginkgo/lib.go [hunk 1]
```diff
@@ -475,7 +475,7 @@ func (ns NsWrapper) RetrieveStatusFromNodetool(podName string) []NodetoolNodeInf
 	nodeTexts := regexp.MustCompile(`(?m)^.*(([0-9a-fA-F]+-){4}([0-9a-fA-F]+)).*$`).FindAllString(output, -1)
 	nodeInfo := []NodetoolNodeInfo{}
 	for _, nodeText := range nodeTexts {
-		comps := regexp.MustCompile(`[[:space:]]+`).Split(nodeText, -1)
+		comps := regexp.MustCompile(`[[:space:]]+`).Split(strings.TrimSpace(nodeText), -1)
```
Comment (adutra) [inline tests/util/ginkgo/lib.go:478]: This is because with C* 4 there is some dangling whitespace at the end of the line. This doesn't happen with C* 3.

**Review by burmanm — APPROVED** [review]
