### PR TITLE
prevent infinite loop when seed refresh times out during node failures

### LINKED ISSUE #887: Infinitely terminating instances will block reconcile
### What happened?

We've seen a case where a pod has been stuck to a state of terminating without Kubernetes being unable to recover from this. This has happened with a sequence of two Kubernetes worker nodes going down (intentionally, but without proper cordon/drain) at the same time. What we see is then some interesting behavior where even replacing two nodes is not possible (with one down node this works, but not with two).

In the starting sequence, the seedRefresh will block any attempts to start new nodes as the seedRefresh happens before any fastStart or normal bootstrapping:

```
2026-01-27T15:59:27.402Z	ERROR	controllers.CassandraDatacenter	calculateReconciliationActions returned an error	{"cassandradatacenter": {"name":"test1-dc1","namespace":"p1-4e85bcg0"}, "requestNamespace": "p1-4e85bcg0", "requestName": "test1-dc1", "loopID": "0458905a-6881-49f1-9944-18da2194dbdf", "error": "Post \"https://192.168.66.30:8080/api/v0/ops/seeds/reload\": context deadline exceeded"}
```

This will then cause reconcile and the loop continues forever. This one is tricky in that technically we could have a pod with incorrect seeds still. In reality, this is probably not as big of a problem as we tend to have 3 seed nodes so even if one is in the wrong state, everything should be fine (and new bootstrapping nodes should have DNS refresh in any case).

Second issue comes that this pod will cause some weird issues in certain other parts of the code, such as:

```
2026-01-28T14:51:59.500Z	ERROR	Observed a panic	{"controller": "cassandradatacenter_controller", "controllerGroup": "cassandra.datastax.com", "controllerKind": "CassandraDatacenter", "CassandraDatacenter": {"name":"test-dc1","namespace":"p2-311t5u4p"}, "namespace": "p2-311t5u4p", "name": "test-dc1", "reconcileID": "aac79841-fc1c-4bfd-bbf6-e909eea980ea", "panic": "runtime error: invalid memory address or nil pointer dereference", "panicGoValue": "\"invalid memory address or nil pointer dereference\"", "stacktrace": "goroutine 285 [running]:\nk8s.io/apimachinery/pkg/util/runtime.logPanic({0x2518b88, 0xc0015fe9c0}, {0x1e7c6c0, 0x37304d0})\n\t/go/pkg/mod/k8s.io/apimachinery@v0.33.3/pkg/util/runtime/runtime.go:132 +0xbc\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile.func1()\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:108 +0x112\npanic({0x1e7c6c0?, 0x37304d0?})\n\t/usr/local/go/src/runtime/panic.go:792 +0x132\ngithub.com/k8ssandra/cass-operator/pkg/reconciliation.isServerReady(...)\n\t/workspace/pkg/reconciliation/reconcile_racks.go:2249\ngithub.com/k8ssandra/cass-operator/pkg/reconciliation.(*ReconciliationContext).createStartSequence(0xc000da28c0)\n\t/workspace/pkg/reconciliation/reconcile_racks.go:2113 +0x386\ngithub.com/k8ssandra/cass-operator/pkg/reconciliation.(*ReconciliationContext).startAllNodes(0xc000da28c0, {{0xc000c42008?, 0x21eec25?, 0x21d04c4?}})\n\t/workspace/pkg/reconciliation/reconcile_racks.go:2088 +0x6a\ngithub.com/k8ssandra/cass-operator/pkg/reconciliation.(*ReconciliationContext).CheckPodsReady(0xc000da28c0, {{0xc000c42008?, 0x21cd80c?, 0x1e?}})\n\t/workspace/pkg/reconciliation/reconcile_racks.go:801 +0x6e5\ngithub.com/k8ssandra/cass-operator/pkg/reconciliation.(*ReconciliationContext).ReconcileAllRacks(0xc000da28c0)\n\t/workspace/pkg/reconciliation/reconcile_racks.go:2694 +0x4ed\ngithub.com/k8ssandra/cass-operator/pkg/reconciliation.(*ReconciliationContext).CalculateReconciliationActions(0xc000da28c0)\n\t/workspace/pkg/reconciliation/handler.go:70 +0xc5\ngithub.com/k8ssandra/cass-operator/internal/controllers/cassandra.(*CassandraDatacenterReconciler).Reconcile(0xc000029590, {0x2518b88, 0xc0015fe9c0}, {{{0xc0012cfb50, 0xb}, {0xc0012cfbb0, 0x8}}})\n\t/workspace/internal/controllers/cassandra/cassandradatacenter_controller.go:147 +0xa3a\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile(0xc0015fe930?, {0x2518b88?, 0xc0015fe9c0?}, {{{0xc0012cfb50?, 0x0?}, {0xc0012cfbb0?, 0x0?}}})\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:119 +0xbf\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler(0x25430c0, {0x2518bc0, 0xc0000294a0}, {{{0xc0012cfb50, 0xb}, {0xc0012cfbb0, 0x8}}}, 0x0)\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:340 +0x3ad\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem(0x25430c0, {0x2518bc0, 0xc0000294a0})\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:300 +0x21b\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.1()\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:202 +0x85\ncreated by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2 in goroutine 76\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:198 +0x28f\n"}
```

This is probably caused by the Pod missing some fields. We might need to be more defensive here, but also we would probably require something to avoid incorrect pods from blocking everything. Yet, I'm not sure how we can detect these from real terminating pods which can take a while and that's perfectly normal. 

### What did you expect to happen?

I'd expect cass-operator able to recover from this state without large manual process. I'd say this requires some investigation into how refreshSeeds is required as a process at this point when pods have anyway bootstrapped and if we really need to call it so often or block processing otherwise. It's not necessarily true that just fixing this would solve the issue, but this is the first step for investigation.

### How can we reproduce it (as minimally and precisely as possible)?

B) Two nodes down - replacenode does not work
* 4 nodes DSE cluster
* Stop the AWS instance for TWO of the k8s worker nodes
* The DSE node pods on the down k8s worker nodes go into Terminating state
* Create a replacenode cassandratask for ONE of the down node. I was thinking to try replace one by one
* run kubectl delete pod <terminating pod with replacenode task> --force. 
* A new DSE node pod is created on a new k8s worker node. But it does not start. Its stuck in the 1/2 Running state for over an hour.
* At this point I thought maybe replacing the other node might do somthing:
  * Create a replacenode cassandratask for OTHER of the down node
  * run kubectl delete pod <terminating pod with new replacenode task> --force
  * A new DSE node pod is created on a new k8s worker node. But it does not start. Its stuck in the 1/2 Running state 
* Now both nodes (sts-1, sts-2) are in a loop of Init -> Running 1/2 (DSE never tries to start)  -> Wait ~10 mins -> Terminating

### cass-operator version

1.28

### Kubernetes version

Unknown

### Method of installation

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by artsiom-bukhautsou**
**What this PR does**:
Prevents infinite loop when seed refresh times out during node failures, allowing the operator to recover.

**Which issue(s) this PR fixes**:
Fixes #887 

**Checklist**
- [X] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CHANGELOG.md updated (not required for documentation PRs)
- [X] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: pkg/reconciliation/reconcile_racks.go [hunk 1]
```diff
@@ -704,18 +704,21 @@ func (rc *ReconciliationContext) CheckRackStoppedState() result.ReconcileResult
 }
 
 // checkSeedLabels loops over all racks and makes sure that the proper pods are labelled as seeds.
-func (rc *ReconciliationContext) checkSeedLabels() (int, error) {
+func (rc *ReconciliationContext) checkSeedLabels() (seedCount int, didSeedsChange bool, err error) {
```
Comment (burmanm) [inline pkg/reconciliation/reconcile_racks.go]: Lets not use any named return values, there's no real use case here. int, bool, err is fine.

File: pkg/reconciliation/reconcile_racks.go [hunk 2]
```diff
@@ -2139,6 +2145,13 @@ func (rc *ReconciliationContext) createStartSequence() []*corev1.Pod {
 		for podRankWithinRack := maxPodRankInThisRack; podRankWithinRack >= 0; podRankWithinRack-- {
 			podName := getStatefulSetPodNameForIdx(statefulSet, int32(podRankWithinRack))
 			pod := rc.getDCPodByName(podName)
+			if pod == nil {
```
Comment (burmanm) [inline pkg/reconciliation/reconcile_racks.go:2156]: issue: This could modify behavior later down the line. If the StatefulSet controller hasn't caught up and we don't have a pod, we might be applying changes to the StatefulSets that were not intended to be happening yet. Did you verify this situation is caught later in the sequence by the StS checks?

File: pkg/reconciliation/reconcile_racks_test.go [hunk 3]
```diff
@@ -4155,3 +4155,139 @@ func TestCheckDcPodDisruptionBudget(t *testing.T) {
 	pdb = &policyv1.PodDisruptionBudget{}
 	require.NoError(rc.Client.Get(rc.Ctx, pdbName, pdb))
 }
+
+func TestRefreshSeeds(t *testing.T) {
+	assert := assert.New(t)
+	const (
```
Comment (burmanm) [inline pkg/reconciliation/reconcile_racks_test.go]: question: const inside a test function?

File: pkg/reconciliation/reconcile_racks.go (hunk 1 above)
Comment (artsiom-bukhautsou) [reply pkg/reconciliation/reconcile_racks.go]: Agree fixed

File: pkg/reconciliation/reconcile_racks.go (hunk 2 above)
Comment (artsiom-bukhautsou) [reply pkg/reconciliation/reconcile_racks.go:2156]: No, I didn't check it. But after you pointed out I see that we'll catch this on step 5, because of this condition
```go
desiredSize <= readyPodCount
```

Anyways, I agree that  it would be better to catch it at the level of `startAllNodes` since its purpose is to ensure that all nodes are ready. I changed it to return an error to be safe.

File: pkg/reconciliation/reconcile_racks_test.go (hunk 3 above)
Comment (artsiom-bukhautsou) [reply pkg/reconciliation/reconcile_racks_test.go]: it's more like personal preference to show that these variables shouldn't be changed. But probably overkill for the tests. Fixed.

**Review by burmanm — APPROVED** [review]
