### PR TITLE
Replace all invalid characters from rackNames when used in Kubernetes

### LINKED ISSUE #404: K8SSAND-1772 ⁃ User rackName should not be trusted
**What happened?**
If user enters a rackName that can't be used as is on the Kubernetes side, we should be filtering all the non-accepted characters from it.

See https://github.com/k8ssandra/k8ssandra-operator/issues/673 for more details.

**Did you expect to see something different?**

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* Cass Operator version:

    `Insert image tag or Git SHA here`
    
    * Kubernetes version information:

    `kubectl version`
    * Kubernetes cluster kind:

```
insert how you created your cluster: kops, bootkube, etc.
```

* Manifests:

```
insert manifests relevant to the issue
```

* Cass Operator Logs:

```
insert Cass Operator logs relevant to the issue here
```

**Anything else we need to know?**:

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1772) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1772
┆priority: Medium

### PR DESCRIPTION
**Pull request by burmanm**
… labels or resource names.

**What this PR does**:
If rackName contains characters or structure that's not accepted by the Kubernetes (in label values or in constructed resource names), remove those invalid characters.

While for new clusters it makes more sense to reject them, we have to reserve them for older ones migrating to Kubernetes.

**Which issue(s) this PR fixes**:
Fixes #404 

**Checklist**
- [x] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CHANGELOG.md updated (not required for documentation PRs)
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: apis/cassandra/v1beta1/cassandradatacenter_types.go [hunk 1]
```diff
@@ -555,23 +555,44 @@ func (dc *CassandraDatacenter) GetClusterLabels() map[string]string {
 	}
 }
 
-// apimachinery validation does not expose this, copied here
-const dns1035LabelFmt string = "[a-z]([-a-z0-9]*[a-z0-9])?"
+// apimachinery validation does not expose these, copied here
+const (
+	dns1035LabelFmt     string = "[a-z]([-a-z0-9]*[a-z0-9])?"
+	dns1123SubdomainFmt string = "[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*"
+	labelFmt            string = "(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?"
```
Comment (adutra) [inline apis/cassandra/v1beta1/cassandradatacenter_types.go]: Nit: rename to `dns1123LabelFmt` like the others above.

File: pkg/reconciliation/construct_statefulset.go [hunk 2]
```diff
@@ -27,7 +27,7 @@ func newNamespacedNameForStatefulSet(
 	dc *api.CassandraDatacenter,
 	rackName string) types.NamespacedName {
 
-	name := api.CleanupForKubernetes(dc.Spec.ClusterName) + "-" + dc.Name + "-" + rackName + "-sts"
+	name := api.CleanupForKubernetes(dc.Spec.ClusterName) + "-" + dc.Name + "-" + api.CleanupSubdomain(rackName) + "-sts"
```
Comment (adutra) [inline pkg/reconciliation/construct_statefulset.go:30]: I think this could be simplified to:

```suggestion
	name := api.CleanupForKubernetes(dc.Spec.ClusterName + "-" + dc.Name + "-" + rackName + "-sts")
```

Because the real requirement is that `name` must conform to RFC 1035. IOW: if `dc.Spec.ClusterName` conforms to RFC 1035 and `rackName` conforms to RFC 1123, then the concatenation of both with a dash also conforms to RFC 1035.

File: pkg/reconciliation/construct_statefulset_test.go [hunk 3]
```diff
@@ -450,6 +451,44 @@ func Test_newStatefulSetForCassandraPodSecurityContext(t *testing.T) {
 	}
 }
 
+func TestValidName(t *testing.T) {
```
Comment (adutra) [inline pkg/reconciliation/construct_statefulset_test.go]: These tests are good but if we have time to do it, it would be even better to have individual tests for `CleanupForKubernetes`, `CleanupSubdomain` and `CleanLabelValue` :-)

Comment (burmanm) [reply pkg/reconciliation/construct_statefulset_test.go]: I'll rename this to indicate it tests subdomain, but we do have those other tests. labels_test.go has one for CleanLabelValue and CleanupForKubernetes is tested in some other test as part of the process (but of course now I can't remember where - but at least Test_buildDefaultSuperuserSecret has a small test).

File: pkg/reconciliation/construct_statefulset.go (hunk 2 above)
Comment (burmanm) [reply pkg/reconciliation/construct_statefulset.go:30]: Actually, this resulted in incorrect result:

        	Error:      	Not equal:
        	            	expected: "cluster1-dc1-invalid-pod-name-sts"
        	            	actual  : "cluster1-dc1-invalid-pod-namests"

Comment (adutra) [reply pkg/reconciliation/construct_statefulset.go:30]: I don't see why one dash would be removed and not the others, but OK.

**Review by adutra — APPROVED** [review]

File: pkg/reconciliation/construct_statefulset.go (hunk 2 above)
Comment (burmanm) [reply pkg/reconciliation/construct_statefulset.go:30]: The 1035 does not allow dashes in every position (and not just the beginning). Not that I could directly say why that forth position from the end is not allowing it..
